# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='instance.proto',
  package='openmit.pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0einstance.proto\x12\nopenmit.pb\"\x16\n\x05Label\x12\r\n\x05label\x18\x01 \x03(\x02\"M\n\x07\x46\x65\x61ture\x12\x0b\n\x03tag\x18\x01 \x01(\x04\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x0b\n\x03val\x18\x03 \x01(\x02\x12\x0e\n\x06weight\x18\x04 \x01(\x02\x12\x0c\n\x04type\x18\x05 \x01(\t\",\n\x0c\x44\x65nseFeature\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\"Y\n\x08\x46\x65\x61tures\x12$\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32\x13.openmit.pb.Feature\x12\'\n\x05\x64\x65nse\x18\x02 \x03(\x0b\x32\x18.openmit.pb.DenseFeature\"\x8a\x01\n\x08Instance\x12\x0f\n\x07inst_id\x18\x01 \x01(\x04\x12\x13\n\x0binst_weight\x18\x02 \x01(\x02\x12 \n\x05label\x18\x03 \x01(\x0b\x32\x11.openmit.pb.Label\x12&\n\x08\x66\x65\x61tures\x18\x04 \x01(\x0b\x32\x14.openmit.pb.Features\x12\x0e\n\x06seq_id\x18\x05 \x01(\r\"\xac\x01\n\tInstances\x12\'\n\tinstances\x18\x01 \x03(\x0b\x32\x14.openmit.pb.Instance\x12\r\n\x05logid\x18\x02 \x01(\x04\x12\x36\n\tmeta_info\x18\x03 \x03(\x0b\x32#.openmit.pb.Instances.MetaInfoEntry\x1a/\n\rMetaInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42(\n\x11org.openmit.entryB\x0eInstanceProtosP\x01\xf8\x01\x01\x62\x06proto3')
)




_LABEL = _descriptor.Descriptor(
  name='Label',
  full_name='openmit.pb.Label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='openmit.pb.Label.label', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=52,
)


_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='openmit.pb.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='openmit.pb.Feature.tag', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='openmit.pb.Feature.id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='openmit.pb.Feature.val', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='openmit.pb.Feature.weight', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='openmit.pb.Feature.type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=131,
)


_DENSEFEATURE = _descriptor.Descriptor(
  name='DenseFeature',
  full_name='openmit.pb.DenseFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='openmit.pb.DenseFeature.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='openmit.pb.DenseFeature.values', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=177,
)


_FEATURES = _descriptor.Descriptor(
  name='Features',
  full_name='openmit.pb.Features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='openmit.pb.Features.feature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dense', full_name='openmit.pb.Features.dense', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=268,
)


_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='openmit.pb.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inst_id', full_name='openmit.pb.Instance.inst_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inst_weight', full_name='openmit.pb.Instance.inst_weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='openmit.pb.Instance.label', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='openmit.pb.Instance.features', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq_id', full_name='openmit.pb.Instance.seq_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=409,
)


_INSTANCES_METAINFOENTRY = _descriptor.Descriptor(
  name='MetaInfoEntry',
  full_name='openmit.pb.Instances.MetaInfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='openmit.pb.Instances.MetaInfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='openmit.pb.Instances.MetaInfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=584,
)

_INSTANCES = _descriptor.Descriptor(
  name='Instances',
  full_name='openmit.pb.Instances',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instances', full_name='openmit.pb.Instances.instances', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logid', full_name='openmit.pb.Instances.logid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta_info', full_name='openmit.pb.Instances.meta_info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INSTANCES_METAINFOENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=584,
)

_FEATURES.fields_by_name['feature'].message_type = _FEATURE
_FEATURES.fields_by_name['dense'].message_type = _DENSEFEATURE
_INSTANCE.fields_by_name['label'].message_type = _LABEL
_INSTANCE.fields_by_name['features'].message_type = _FEATURES
_INSTANCES_METAINFOENTRY.containing_type = _INSTANCES
_INSTANCES.fields_by_name['instances'].message_type = _INSTANCE
_INSTANCES.fields_by_name['meta_info'].message_type = _INSTANCES_METAINFOENTRY
DESCRIPTOR.message_types_by_name['Label'] = _LABEL
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['DenseFeature'] = _DENSEFEATURE
DESCRIPTOR.message_types_by_name['Features'] = _FEATURES
DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
DESCRIPTOR.message_types_by_name['Instances'] = _INSTANCES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), dict(
  DESCRIPTOR = _LABEL,
  __module__ = 'instance_pb2'
  # @@protoc_insertion_point(class_scope:openmit.pb.Label)
  ))
_sym_db.RegisterMessage(Label)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), dict(
  DESCRIPTOR = _FEATURE,
  __module__ = 'instance_pb2'
  # @@protoc_insertion_point(class_scope:openmit.pb.Feature)
  ))
_sym_db.RegisterMessage(Feature)

DenseFeature = _reflection.GeneratedProtocolMessageType('DenseFeature', (_message.Message,), dict(
  DESCRIPTOR = _DENSEFEATURE,
  __module__ = 'instance_pb2'
  # @@protoc_insertion_point(class_scope:openmit.pb.DenseFeature)
  ))
_sym_db.RegisterMessage(DenseFeature)

Features = _reflection.GeneratedProtocolMessageType('Features', (_message.Message,), dict(
  DESCRIPTOR = _FEATURES,
  __module__ = 'instance_pb2'
  # @@protoc_insertion_point(class_scope:openmit.pb.Features)
  ))
_sym_db.RegisterMessage(Features)

Instance = _reflection.GeneratedProtocolMessageType('Instance', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCE,
  __module__ = 'instance_pb2'
  # @@protoc_insertion_point(class_scope:openmit.pb.Instance)
  ))
_sym_db.RegisterMessage(Instance)

Instances = _reflection.GeneratedProtocolMessageType('Instances', (_message.Message,), dict(

  MetaInfoEntry = _reflection.GeneratedProtocolMessageType('MetaInfoEntry', (_message.Message,), dict(
    DESCRIPTOR = _INSTANCES_METAINFOENTRY,
    __module__ = 'instance_pb2'
    # @@protoc_insertion_point(class_scope:openmit.pb.Instances.MetaInfoEntry)
    ))
  ,
  DESCRIPTOR = _INSTANCES,
  __module__ = 'instance_pb2'
  # @@protoc_insertion_point(class_scope:openmit.pb.Instances)
  ))
_sym_db.RegisterMessage(Instances)
_sym_db.RegisterMessage(Instances.MetaInfoEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021org.openmit.entryB\016InstanceProtosP\001\370\001\001'))
_INSTANCES_METAINFOENTRY.has_options = True
_INSTANCES_METAINFOENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
