// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instance.proto

package org.openmit.entry;

/**
 * Protobuf type {@code openmit.pb.Features}
 */
public  final class Features extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:openmit.pb.Features)
    FeaturesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Features.newBuilder() to construct.
  private Features(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Features() {
    feature_ = java.util.Collections.emptyList();
    dense_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Features(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              feature_ = new java.util.ArrayList<org.openmit.entry.Feature>();
              mutable_bitField0_ |= 0x00000001;
            }
            feature_.add(
                input.readMessage(org.openmit.entry.Feature.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              dense_ = new java.util.ArrayList<org.openmit.entry.DenseFeature>();
              mutable_bitField0_ |= 0x00000002;
            }
            dense_.add(
                input.readMessage(org.openmit.entry.DenseFeature.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        feature_ = java.util.Collections.unmodifiableList(feature_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        dense_ = java.util.Collections.unmodifiableList(dense_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Features_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Features_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmit.entry.Features.class, org.openmit.entry.Features.Builder.class);
  }

  public static final int FEATURE_FIELD_NUMBER = 1;
  private java.util.List<org.openmit.entry.Feature> feature_;
  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  public java.util.List<org.openmit.entry.Feature> getFeatureList() {
    return feature_;
  }
  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  public java.util.List<? extends org.openmit.entry.FeatureOrBuilder> 
      getFeatureOrBuilderList() {
    return feature_;
  }
  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  public int getFeatureCount() {
    return feature_.size();
  }
  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  public org.openmit.entry.Feature getFeature(int index) {
    return feature_.get(index);
  }
  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  public org.openmit.entry.FeatureOrBuilder getFeatureOrBuilder(
      int index) {
    return feature_.get(index);
  }

  public static final int DENSE_FIELD_NUMBER = 2;
  private java.util.List<org.openmit.entry.DenseFeature> dense_;
  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  public java.util.List<org.openmit.entry.DenseFeature> getDenseList() {
    return dense_;
  }
  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  public java.util.List<? extends org.openmit.entry.DenseFeatureOrBuilder> 
      getDenseOrBuilderList() {
    return dense_;
  }
  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  public int getDenseCount() {
    return dense_.size();
  }
  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  public org.openmit.entry.DenseFeature getDense(int index) {
    return dense_.get(index);
  }
  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  public org.openmit.entry.DenseFeatureOrBuilder getDenseOrBuilder(
      int index) {
    return dense_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < feature_.size(); i++) {
      output.writeMessage(1, feature_.get(i));
    }
    for (int i = 0; i < dense_.size(); i++) {
      output.writeMessage(2, dense_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < feature_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, feature_.get(i));
    }
    for (int i = 0; i < dense_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, dense_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmit.entry.Features)) {
      return super.equals(obj);
    }
    org.openmit.entry.Features other = (org.openmit.entry.Features) obj;

    boolean result = true;
    result = result && getFeatureList()
        .equals(other.getFeatureList());
    result = result && getDenseList()
        .equals(other.getDenseList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFeatureCount() > 0) {
      hash = (37 * hash) + FEATURE_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureList().hashCode();
    }
    if (getDenseCount() > 0) {
      hash = (37 * hash) + DENSE_FIELD_NUMBER;
      hash = (53 * hash) + getDenseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmit.entry.Features parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmit.entry.Features parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmit.entry.Features parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmit.entry.Features parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmit.entry.Features parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmit.entry.Features parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmit.entry.Features parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.openmit.entry.Features parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmit.entry.Features parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.openmit.entry.Features parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmit.entry.Features parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.openmit.entry.Features parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmit.entry.Features prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code openmit.pb.Features}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:openmit.pb.Features)
      org.openmit.entry.FeaturesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Features_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Features_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmit.entry.Features.class, org.openmit.entry.Features.Builder.class);
    }

    // Construct using org.openmit.entry.Features.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFeatureFieldBuilder();
        getDenseFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (featureBuilder_ == null) {
        feature_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        featureBuilder_.clear();
      }
      if (denseBuilder_ == null) {
        dense_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        denseBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Features_descriptor;
    }

    public org.openmit.entry.Features getDefaultInstanceForType() {
      return org.openmit.entry.Features.getDefaultInstance();
    }

    public org.openmit.entry.Features build() {
      org.openmit.entry.Features result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.openmit.entry.Features buildPartial() {
      org.openmit.entry.Features result = new org.openmit.entry.Features(this);
      int from_bitField0_ = bitField0_;
      if (featureBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          feature_ = java.util.Collections.unmodifiableList(feature_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.feature_ = feature_;
      } else {
        result.feature_ = featureBuilder_.build();
      }
      if (denseBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          dense_ = java.util.Collections.unmodifiableList(dense_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.dense_ = dense_;
      } else {
        result.dense_ = denseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmit.entry.Features) {
        return mergeFrom((org.openmit.entry.Features)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmit.entry.Features other) {
      if (other == org.openmit.entry.Features.getDefaultInstance()) return this;
      if (featureBuilder_ == null) {
        if (!other.feature_.isEmpty()) {
          if (feature_.isEmpty()) {
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFeatureIsMutable();
            feature_.addAll(other.feature_);
          }
          onChanged();
        }
      } else {
        if (!other.feature_.isEmpty()) {
          if (featureBuilder_.isEmpty()) {
            featureBuilder_.dispose();
            featureBuilder_ = null;
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00000001);
            featureBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFeatureFieldBuilder() : null;
          } else {
            featureBuilder_.addAllMessages(other.feature_);
          }
        }
      }
      if (denseBuilder_ == null) {
        if (!other.dense_.isEmpty()) {
          if (dense_.isEmpty()) {
            dense_ = other.dense_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDenseIsMutable();
            dense_.addAll(other.dense_);
          }
          onChanged();
        }
      } else {
        if (!other.dense_.isEmpty()) {
          if (denseBuilder_.isEmpty()) {
            denseBuilder_.dispose();
            denseBuilder_ = null;
            dense_ = other.dense_;
            bitField0_ = (bitField0_ & ~0x00000002);
            denseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDenseFieldBuilder() : null;
          } else {
            denseBuilder_.addAllMessages(other.dense_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.openmit.entry.Features parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.openmit.entry.Features) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.openmit.entry.Feature> feature_ =
      java.util.Collections.emptyList();
    private void ensureFeatureIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        feature_ = new java.util.ArrayList<org.openmit.entry.Feature>(feature_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.openmit.entry.Feature, org.openmit.entry.Feature.Builder, org.openmit.entry.FeatureOrBuilder> featureBuilder_;

    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public java.util.List<org.openmit.entry.Feature> getFeatureList() {
      if (featureBuilder_ == null) {
        return java.util.Collections.unmodifiableList(feature_);
      } else {
        return featureBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public int getFeatureCount() {
      if (featureBuilder_ == null) {
        return feature_.size();
      } else {
        return featureBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public org.openmit.entry.Feature getFeature(int index) {
      if (featureBuilder_ == null) {
        return feature_.get(index);
      } else {
        return featureBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public Builder setFeature(
        int index, org.openmit.entry.Feature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeatureIsMutable();
        feature_.set(index, value);
        onChanged();
      } else {
        featureBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public Builder setFeature(
        int index, org.openmit.entry.Feature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.set(index, builderForValue.build());
        onChanged();
      } else {
        featureBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public Builder addFeature(org.openmit.entry.Feature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeatureIsMutable();
        feature_.add(value);
        onChanged();
      } else {
        featureBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public Builder addFeature(
        int index, org.openmit.entry.Feature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeatureIsMutable();
        feature_.add(index, value);
        onChanged();
      } else {
        featureBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public Builder addFeature(
        org.openmit.entry.Feature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.add(builderForValue.build());
        onChanged();
      } else {
        featureBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public Builder addFeature(
        int index, org.openmit.entry.Feature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.add(index, builderForValue.build());
        onChanged();
      } else {
        featureBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public Builder addAllFeature(
        java.lang.Iterable<? extends org.openmit.entry.Feature> values) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, feature_);
        onChanged();
      } else {
        featureBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public Builder clearFeature() {
      if (featureBuilder_ == null) {
        feature_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        featureBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public Builder removeFeature(int index) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.remove(index);
        onChanged();
      } else {
        featureBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public org.openmit.entry.Feature.Builder getFeatureBuilder(
        int index) {
      return getFeatureFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public org.openmit.entry.FeatureOrBuilder getFeatureOrBuilder(
        int index) {
      if (featureBuilder_ == null) {
        return feature_.get(index);  } else {
        return featureBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public java.util.List<? extends org.openmit.entry.FeatureOrBuilder> 
         getFeatureOrBuilderList() {
      if (featureBuilder_ != null) {
        return featureBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(feature_);
      }
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public org.openmit.entry.Feature.Builder addFeatureBuilder() {
      return getFeatureFieldBuilder().addBuilder(
          org.openmit.entry.Feature.getDefaultInstance());
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public org.openmit.entry.Feature.Builder addFeatureBuilder(
        int index) {
      return getFeatureFieldBuilder().addBuilder(
          index, org.openmit.entry.Feature.getDefaultInstance());
    }
    /**
     * <code>repeated .openmit.pb.Feature feature = 1;</code>
     */
    public java.util.List<org.openmit.entry.Feature.Builder> 
         getFeatureBuilderList() {
      return getFeatureFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.openmit.entry.Feature, org.openmit.entry.Feature.Builder, org.openmit.entry.FeatureOrBuilder> 
        getFeatureFieldBuilder() {
      if (featureBuilder_ == null) {
        featureBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.openmit.entry.Feature, org.openmit.entry.Feature.Builder, org.openmit.entry.FeatureOrBuilder>(
                feature_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        feature_ = null;
      }
      return featureBuilder_;
    }

    private java.util.List<org.openmit.entry.DenseFeature> dense_ =
      java.util.Collections.emptyList();
    private void ensureDenseIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        dense_ = new java.util.ArrayList<org.openmit.entry.DenseFeature>(dense_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.openmit.entry.DenseFeature, org.openmit.entry.DenseFeature.Builder, org.openmit.entry.DenseFeatureOrBuilder> denseBuilder_;

    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public java.util.List<org.openmit.entry.DenseFeature> getDenseList() {
      if (denseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dense_);
      } else {
        return denseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public int getDenseCount() {
      if (denseBuilder_ == null) {
        return dense_.size();
      } else {
        return denseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public org.openmit.entry.DenseFeature getDense(int index) {
      if (denseBuilder_ == null) {
        return dense_.get(index);
      } else {
        return denseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public Builder setDense(
        int index, org.openmit.entry.DenseFeature value) {
      if (denseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDenseIsMutable();
        dense_.set(index, value);
        onChanged();
      } else {
        denseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public Builder setDense(
        int index, org.openmit.entry.DenseFeature.Builder builderForValue) {
      if (denseBuilder_ == null) {
        ensureDenseIsMutable();
        dense_.set(index, builderForValue.build());
        onChanged();
      } else {
        denseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public Builder addDense(org.openmit.entry.DenseFeature value) {
      if (denseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDenseIsMutable();
        dense_.add(value);
        onChanged();
      } else {
        denseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public Builder addDense(
        int index, org.openmit.entry.DenseFeature value) {
      if (denseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDenseIsMutable();
        dense_.add(index, value);
        onChanged();
      } else {
        denseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public Builder addDense(
        org.openmit.entry.DenseFeature.Builder builderForValue) {
      if (denseBuilder_ == null) {
        ensureDenseIsMutable();
        dense_.add(builderForValue.build());
        onChanged();
      } else {
        denseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public Builder addDense(
        int index, org.openmit.entry.DenseFeature.Builder builderForValue) {
      if (denseBuilder_ == null) {
        ensureDenseIsMutable();
        dense_.add(index, builderForValue.build());
        onChanged();
      } else {
        denseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public Builder addAllDense(
        java.lang.Iterable<? extends org.openmit.entry.DenseFeature> values) {
      if (denseBuilder_ == null) {
        ensureDenseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dense_);
        onChanged();
      } else {
        denseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public Builder clearDense() {
      if (denseBuilder_ == null) {
        dense_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        denseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public Builder removeDense(int index) {
      if (denseBuilder_ == null) {
        ensureDenseIsMutable();
        dense_.remove(index);
        onChanged();
      } else {
        denseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public org.openmit.entry.DenseFeature.Builder getDenseBuilder(
        int index) {
      return getDenseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public org.openmit.entry.DenseFeatureOrBuilder getDenseOrBuilder(
        int index) {
      if (denseBuilder_ == null) {
        return dense_.get(index);  } else {
        return denseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public java.util.List<? extends org.openmit.entry.DenseFeatureOrBuilder> 
         getDenseOrBuilderList() {
      if (denseBuilder_ != null) {
        return denseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dense_);
      }
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public org.openmit.entry.DenseFeature.Builder addDenseBuilder() {
      return getDenseFieldBuilder().addBuilder(
          org.openmit.entry.DenseFeature.getDefaultInstance());
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public org.openmit.entry.DenseFeature.Builder addDenseBuilder(
        int index) {
      return getDenseFieldBuilder().addBuilder(
          index, org.openmit.entry.DenseFeature.getDefaultInstance());
    }
    /**
     * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
     */
    public java.util.List<org.openmit.entry.DenseFeature.Builder> 
         getDenseBuilderList() {
      return getDenseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.openmit.entry.DenseFeature, org.openmit.entry.DenseFeature.Builder, org.openmit.entry.DenseFeatureOrBuilder> 
        getDenseFieldBuilder() {
      if (denseBuilder_ == null) {
        denseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.openmit.entry.DenseFeature, org.openmit.entry.DenseFeature.Builder, org.openmit.entry.DenseFeatureOrBuilder>(
                dense_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        dense_ = null;
      }
      return denseBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:openmit.pb.Features)
  }

  // @@protoc_insertion_point(class_scope:openmit.pb.Features)
  private static final org.openmit.entry.Features DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmit.entry.Features();
  }

  public static org.openmit.entry.Features getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Features>
      PARSER = new com.google.protobuf.AbstractParser<Features>() {
    public Features parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Features(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Features> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Features> getParserForType() {
    return PARSER;
  }

  public org.openmit.entry.Features getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

