// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instance.proto

package org.openmit.entry;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openmit.pb.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 tag = 1;</code>
   */
  long getTag();

  /**
   * <code>uint64 id = 2;</code>
   */
  long getId();

  /**
   * <code>float val = 3;</code>
   */
  float getVal();

  /**
   * <code>float weight = 4;</code>
   */
  float getWeight();

  /**
   * <code>string type = 5;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 5;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
