// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instance.proto

package org.openmit.entry;

public interface FeaturesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openmit.pb.Features)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  java.util.List<org.openmit.entry.Feature> 
      getFeatureList();
  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  org.openmit.entry.Feature getFeature(int index);
  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  java.util.List<? extends org.openmit.entry.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .openmit.pb.Feature feature = 1;</code>
   */
  org.openmit.entry.FeatureOrBuilder getFeatureOrBuilder(
      int index);

  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  java.util.List<org.openmit.entry.DenseFeature> 
      getDenseList();
  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  org.openmit.entry.DenseFeature getDense(int index);
  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  int getDenseCount();
  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  java.util.List<? extends org.openmit.entry.DenseFeatureOrBuilder> 
      getDenseOrBuilderList();
  /**
   * <code>repeated .openmit.pb.DenseFeature dense = 2;</code>
   */
  org.openmit.entry.DenseFeatureOrBuilder getDenseOrBuilder(
      int index);
}
