// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instance.proto

package org.openmit.entry;

public final class InstanceProtos {
  private InstanceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_openmit_pb_Label_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_openmit_pb_Label_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_openmit_pb_Feature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_openmit_pb_Feature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_openmit_pb_DenseFeature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_openmit_pb_DenseFeature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_openmit_pb_Features_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_openmit_pb_Features_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_openmit_pb_Instance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_openmit_pb_Instance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_openmit_pb_Instances_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_openmit_pb_Instances_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_openmit_pb_Instances_MetaInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_openmit_pb_Instances_MetaInfoEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016instance.proto\022\nopenmit.pb\"\026\n\005Label\022\r\n" +
      "\005label\030\001 \003(\002\"M\n\007Feature\022\013\n\003tag\030\001 \001(\004\022\n\n\002" +
      "id\030\002 \001(\004\022\013\n\003val\030\003 \001(\002\022\016\n\006weight\030\004 \001(\002\022\014\n" +
      "\004type\030\005 \001(\t\",\n\014DenseFeature\022\014\n\004type\030\001 \001(" +
      "\t\022\016\n\006values\030\002 \003(\002\"Y\n\010Features\022$\n\007feature" +
      "\030\001 \003(\0132\023.openmit.pb.Feature\022\'\n\005dense\030\002 \003" +
      "(\0132\030.openmit.pb.DenseFeature\"\212\001\n\010Instanc" +
      "e\022\017\n\007inst_id\030\001 \001(\004\022\023\n\013inst_weight\030\002 \001(\002\022" +
      " \n\005label\030\003 \001(\0132\021.openmit.pb.Label\022&\n\010fea" +
      "tures\030\004 \001(\0132\024.openmit.pb.Features\022\016\n\006seq" +
      "_id\030\005 \001(\r\"\254\001\n\tInstances\022\'\n\tinstances\030\001 \003" +
      "(\0132\024.openmit.pb.Instance\022\r\n\005logid\030\002 \001(\004\022" +
      "6\n\tmeta_info\030\003 \003(\0132#.openmit.pb.Instance" +
      "s.MetaInfoEntry\032/\n\rMetaInfoEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B(\n\021org.openmit." +
      "entryB\016InstanceProtosP\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_openmit_pb_Label_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_openmit_pb_Label_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_openmit_pb_Label_descriptor,
        new java.lang.String[] { "Label", });
    internal_static_openmit_pb_Feature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_openmit_pb_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_openmit_pb_Feature_descriptor,
        new java.lang.String[] { "Tag", "Id", "Val", "Weight", "Type", });
    internal_static_openmit_pb_DenseFeature_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_openmit_pb_DenseFeature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_openmit_pb_DenseFeature_descriptor,
        new java.lang.String[] { "Type", "Values", });
    internal_static_openmit_pb_Features_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_openmit_pb_Features_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_openmit_pb_Features_descriptor,
        new java.lang.String[] { "Feature", "Dense", });
    internal_static_openmit_pb_Instance_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_openmit_pb_Instance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_openmit_pb_Instance_descriptor,
        new java.lang.String[] { "InstId", "InstWeight", "Label", "Features", "SeqId", });
    internal_static_openmit_pb_Instances_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_openmit_pb_Instances_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_openmit_pb_Instances_descriptor,
        new java.lang.String[] { "Instances", "Logid", "MetaInfo", });
    internal_static_openmit_pb_Instances_MetaInfoEntry_descriptor =
      internal_static_openmit_pb_Instances_descriptor.getNestedTypes().get(0);
    internal_static_openmit_pb_Instances_MetaInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_openmit_pb_Instances_MetaInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
