// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instance.proto

package org.openmit.entry;

/**
 * Protobuf type {@code openmit.pb.Instances}
 */
public  final class Instances extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:openmit.pb.Instances)
    InstancesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Instances.newBuilder() to construct.
  private Instances(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Instances() {
    instances_ = java.util.Collections.emptyList();
    logid_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Instances(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              instances_ = new java.util.ArrayList<org.openmit.entry.Instance>();
              mutable_bitField0_ |= 0x00000001;
            }
            instances_.add(
                input.readMessage(org.openmit.entry.Instance.parser(), extensionRegistry));
            break;
          }
          case 16: {

            logid_ = input.readUInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              metaInfo_ = com.google.protobuf.MapField.newMapField(
                  MetaInfoDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            metaInfo__ = input.readMessage(
                MetaInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            metaInfo_.getMutableMap().put(
                metaInfo__.getKey(), metaInfo__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        instances_ = java.util.Collections.unmodifiableList(instances_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Instances_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetMetaInfo();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Instances_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmit.entry.Instances.class, org.openmit.entry.Instances.Builder.class);
  }

  private int bitField0_;
  public static final int INSTANCES_FIELD_NUMBER = 1;
  private java.util.List<org.openmit.entry.Instance> instances_;
  /**
   * <code>repeated .openmit.pb.Instance instances = 1;</code>
   */
  public java.util.List<org.openmit.entry.Instance> getInstancesList() {
    return instances_;
  }
  /**
   * <code>repeated .openmit.pb.Instance instances = 1;</code>
   */
  public java.util.List<? extends org.openmit.entry.InstanceOrBuilder> 
      getInstancesOrBuilderList() {
    return instances_;
  }
  /**
   * <code>repeated .openmit.pb.Instance instances = 1;</code>
   */
  public int getInstancesCount() {
    return instances_.size();
  }
  /**
   * <code>repeated .openmit.pb.Instance instances = 1;</code>
   */
  public org.openmit.entry.Instance getInstances(int index) {
    return instances_.get(index);
  }
  /**
   * <code>repeated .openmit.pb.Instance instances = 1;</code>
   */
  public org.openmit.entry.InstanceOrBuilder getInstancesOrBuilder(
      int index) {
    return instances_.get(index);
  }

  public static final int LOGID_FIELD_NUMBER = 2;
  private long logid_;
  /**
   * <code>uint64 logid = 2;</code>
   */
  public long getLogid() {
    return logid_;
  }

  public static final int META_INFO_FIELD_NUMBER = 3;
  private static final class MetaInfoDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Instances_MetaInfoEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metaInfo_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetaInfo() {
    if (metaInfo_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetaInfoDefaultEntryHolder.defaultEntry);
    }
    return metaInfo_;
  }

  public int getMetaInfoCount() {
    return internalGetMetaInfo().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; meta_info = 3;</code>
   */

  public boolean containsMetaInfo(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMetaInfo().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetaInfoMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetaInfo() {
    return getMetaInfoMap();
  }
  /**
   * <code>map&lt;string, string&gt; meta_info = 3;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getMetaInfoMap() {
    return internalGetMetaInfo().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; meta_info = 3;</code>
   */

  public java.lang.String getMetaInfoOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetaInfo().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; meta_info = 3;</code>
   */

  public java.lang.String getMetaInfoOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetaInfo().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < instances_.size(); i++) {
      output.writeMessage(1, instances_.get(i));
    }
    if (logid_ != 0L) {
      output.writeUInt64(2, logid_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMetaInfo(),
        MetaInfoDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < instances_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, instances_.get(i));
    }
    if (logid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, logid_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetaInfo().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metaInfo__ = MetaInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, metaInfo__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmit.entry.Instances)) {
      return super.equals(obj);
    }
    org.openmit.entry.Instances other = (org.openmit.entry.Instances) obj;

    boolean result = true;
    result = result && getInstancesList()
        .equals(other.getInstancesList());
    result = result && (getLogid()
        == other.getLogid());
    result = result && internalGetMetaInfo().equals(
        other.internalGetMetaInfo());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInstancesCount() > 0) {
      hash = (37 * hash) + INSTANCES_FIELD_NUMBER;
      hash = (53 * hash) + getInstancesList().hashCode();
    }
    hash = (37 * hash) + LOGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLogid());
    if (!internalGetMetaInfo().getMap().isEmpty()) {
      hash = (37 * hash) + META_INFO_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetaInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmit.entry.Instances parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmit.entry.Instances parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmit.entry.Instances parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmit.entry.Instances parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmit.entry.Instances parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmit.entry.Instances parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmit.entry.Instances parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.openmit.entry.Instances parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmit.entry.Instances parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.openmit.entry.Instances parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmit.entry.Instances parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.openmit.entry.Instances parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmit.entry.Instances prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code openmit.pb.Instances}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:openmit.pb.Instances)
      org.openmit.entry.InstancesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Instances_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMetaInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableMetaInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Instances_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmit.entry.Instances.class, org.openmit.entry.Instances.Builder.class);
    }

    // Construct using org.openmit.entry.Instances.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInstancesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (instancesBuilder_ == null) {
        instances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        instancesBuilder_.clear();
      }
      logid_ = 0L;

      internalGetMutableMetaInfo().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmit.entry.InstanceProtos.internal_static_openmit_pb_Instances_descriptor;
    }

    public org.openmit.entry.Instances getDefaultInstanceForType() {
      return org.openmit.entry.Instances.getDefaultInstance();
    }

    public org.openmit.entry.Instances build() {
      org.openmit.entry.Instances result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.openmit.entry.Instances buildPartial() {
      org.openmit.entry.Instances result = new org.openmit.entry.Instances(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (instancesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          instances_ = java.util.Collections.unmodifiableList(instances_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.instances_ = instances_;
      } else {
        result.instances_ = instancesBuilder_.build();
      }
      result.logid_ = logid_;
      result.metaInfo_ = internalGetMetaInfo();
      result.metaInfo_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmit.entry.Instances) {
        return mergeFrom((org.openmit.entry.Instances)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmit.entry.Instances other) {
      if (other == org.openmit.entry.Instances.getDefaultInstance()) return this;
      if (instancesBuilder_ == null) {
        if (!other.instances_.isEmpty()) {
          if (instances_.isEmpty()) {
            instances_ = other.instances_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInstancesIsMutable();
            instances_.addAll(other.instances_);
          }
          onChanged();
        }
      } else {
        if (!other.instances_.isEmpty()) {
          if (instancesBuilder_.isEmpty()) {
            instancesBuilder_.dispose();
            instancesBuilder_ = null;
            instances_ = other.instances_;
            bitField0_ = (bitField0_ & ~0x00000001);
            instancesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInstancesFieldBuilder() : null;
          } else {
            instancesBuilder_.addAllMessages(other.instances_);
          }
        }
      }
      if (other.getLogid() != 0L) {
        setLogid(other.getLogid());
      }
      internalGetMutableMetaInfo().mergeFrom(
          other.internalGetMetaInfo());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.openmit.entry.Instances parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.openmit.entry.Instances) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.openmit.entry.Instance> instances_ =
      java.util.Collections.emptyList();
    private void ensureInstancesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        instances_ = new java.util.ArrayList<org.openmit.entry.Instance>(instances_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.openmit.entry.Instance, org.openmit.entry.Instance.Builder, org.openmit.entry.InstanceOrBuilder> instancesBuilder_;

    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public java.util.List<org.openmit.entry.Instance> getInstancesList() {
      if (instancesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(instances_);
      } else {
        return instancesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public int getInstancesCount() {
      if (instancesBuilder_ == null) {
        return instances_.size();
      } else {
        return instancesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public org.openmit.entry.Instance getInstances(int index) {
      if (instancesBuilder_ == null) {
        return instances_.get(index);
      } else {
        return instancesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public Builder setInstances(
        int index, org.openmit.entry.Instance value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.set(index, value);
        onChanged();
      } else {
        instancesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public Builder setInstances(
        int index, org.openmit.entry.Instance.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.set(index, builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public Builder addInstances(org.openmit.entry.Instance value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.add(value);
        onChanged();
      } else {
        instancesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public Builder addInstances(
        int index, org.openmit.entry.Instance value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.add(index, value);
        onChanged();
      } else {
        instancesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public Builder addInstances(
        org.openmit.entry.Instance.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.add(builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public Builder addInstances(
        int index, org.openmit.entry.Instance.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.add(index, builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public Builder addAllInstances(
        java.lang.Iterable<? extends org.openmit.entry.Instance> values) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instances_);
        onChanged();
      } else {
        instancesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public Builder clearInstances() {
      if (instancesBuilder_ == null) {
        instances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        instancesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public Builder removeInstances(int index) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.remove(index);
        onChanged();
      } else {
        instancesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public org.openmit.entry.Instance.Builder getInstancesBuilder(
        int index) {
      return getInstancesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public org.openmit.entry.InstanceOrBuilder getInstancesOrBuilder(
        int index) {
      if (instancesBuilder_ == null) {
        return instances_.get(index);  } else {
        return instancesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public java.util.List<? extends org.openmit.entry.InstanceOrBuilder> 
         getInstancesOrBuilderList() {
      if (instancesBuilder_ != null) {
        return instancesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(instances_);
      }
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public org.openmit.entry.Instance.Builder addInstancesBuilder() {
      return getInstancesFieldBuilder().addBuilder(
          org.openmit.entry.Instance.getDefaultInstance());
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public org.openmit.entry.Instance.Builder addInstancesBuilder(
        int index) {
      return getInstancesFieldBuilder().addBuilder(
          index, org.openmit.entry.Instance.getDefaultInstance());
    }
    /**
     * <code>repeated .openmit.pb.Instance instances = 1;</code>
     */
    public java.util.List<org.openmit.entry.Instance.Builder> 
         getInstancesBuilderList() {
      return getInstancesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.openmit.entry.Instance, org.openmit.entry.Instance.Builder, org.openmit.entry.InstanceOrBuilder> 
        getInstancesFieldBuilder() {
      if (instancesBuilder_ == null) {
        instancesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.openmit.entry.Instance, org.openmit.entry.Instance.Builder, org.openmit.entry.InstanceOrBuilder>(
                instances_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        instances_ = null;
      }
      return instancesBuilder_;
    }

    private long logid_ ;
    /**
     * <code>uint64 logid = 2;</code>
     */
    public long getLogid() {
      return logid_;
    }
    /**
     * <code>uint64 logid = 2;</code>
     */
    public Builder setLogid(long value) {
      
      logid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 logid = 2;</code>
     */
    public Builder clearLogid() {
      
      logid_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metaInfo_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetaInfo() {
      if (metaInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaInfoDefaultEntryHolder.defaultEntry);
      }
      return metaInfo_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableMetaInfo() {
      onChanged();;
      if (metaInfo_ == null) {
        metaInfo_ = com.google.protobuf.MapField.newMapField(
            MetaInfoDefaultEntryHolder.defaultEntry);
      }
      if (!metaInfo_.isMutable()) {
        metaInfo_ = metaInfo_.copy();
      }
      return metaInfo_;
    }

    public int getMetaInfoCount() {
      return internalGetMetaInfo().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 3;</code>
     */

    public boolean containsMetaInfo(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMetaInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaInfoMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetaInfo() {
      return getMetaInfoMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getMetaInfoMap() {
      return internalGetMetaInfo().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 3;</code>
     */

    public java.lang.String getMetaInfoOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetaInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 3;</code>
     */

    public java.lang.String getMetaInfoOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetaInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMetaInfo() {
      internalGetMutableMetaInfo().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 3;</code>
     */

    public Builder removeMetaInfo(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMetaInfo().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableMetaInfo() {
      return internalGetMutableMetaInfo().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 3;</code>
     */
    public Builder putMetaInfo(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMetaInfo().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 3;</code>
     */

    public Builder putAllMetaInfo(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetaInfo().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:openmit.pb.Instances)
  }

  // @@protoc_insertion_point(class_scope:openmit.pb.Instances)
  private static final org.openmit.entry.Instances DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmit.entry.Instances();
  }

  public static org.openmit.entry.Instances getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Instances>
      PARSER = new com.google.protobuf.AbstractParser<Instances>() {
    public Instances parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Instances(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Instances> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Instances> getParserForType() {
    return PARSER;
  }

  public org.openmit.entry.Instances getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

