// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instance.proto

package org.openmit.entry;

public interface LabelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openmit.pb.Label)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated float label = 1;</code>
   */
  java.util.List<java.lang.Float> getLabelList();
  /**
   * <code>repeated float label = 1;</code>
   */
  int getLabelCount();
  /**
   * <code>repeated float label = 1;</code>
   */
  float getLabel(int index);
}
